def func_de_erro():
    raise Exception('Meu Erro est√° aqui!')
